export const rawData:object[] = [
  {
    address:"河北省",
    children:[
      {
        address:"石家庄市",
        children:[
          {
            address:"长安区"
          },
          {
            address:"桥西区"
          }
        ]
      },
      {
        address:"唐山市",
        children:[
          {
            address:"路北区"
          },
          {
            address:"路南区"
          }
        ]
      }
    ]
  },
  {
    address:"山西省",
    children:[
      {
        address:"太原市",
        children:[
          {
            address:"小店区"
          },
          {
            address:"迎泽区"
          }
        ]
      },
      {
        address:"大同市",
        children:[
          {
            address:"城区"
          },
          {
            address:"矿区"
          }
        ]
      }
    ]
  }
]